# Generated by Django 5.2.1 on 2025-05-09 12:21

from django.db import migrations


def create_initial_data(apps, schema_editor):
    Unit = apps.get_model('fine_particles', 'Unit')
    MeasurementType = apps.get_model('fine_particles', 'MeasurementType')

    Unit.objects.get_or_create(name='µg/m³')
    MeasurementType.objects.get_or_create(name='PM2.5')
    MeasurementType.objects.get_or_create(name='PM10')


class Migration(migrations.Migration):

    dependencies = [
        ('fine_particles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data),
    ]
